/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_microrisc_rpi_io_SimpleIO */

#ifndef _Included_com_microrisc_rpi_io_SimpleIO
#define _Included_com_microrisc_rpi_io_SimpleIO
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_microrisc_rpi_io_SimpleIO
 * Method:    stub_init
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_microrisc_rpi_io_SimpleIO_stub_1init
  (JNIEnv *, jobject);

/*
 * Class:     com_microrisc_rpi_io_SimpleIO
 * Method:    stub_set
 * Signature: (II)V
 */
JNIEXPORT void JNICALL Java_com_microrisc_rpi_io_SimpleIO_stub_1set
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     com_microrisc_rpi_io_SimpleIO
 * Method:    stub_write
 * Signature: (II)V
 */
JNIEXPORT void JNICALL Java_com_microrisc_rpi_io_SimpleIO_stub_1write
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     com_microrisc_rpi_io_SimpleIO
 * Method:    stub_read
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_com_microrisc_rpi_io_SimpleIO_stub_1read
  (JNIEnv *, jobject, jint);

/*
 * Class:     com_microrisc_rpi_io_SimpleIO
 * Method:    stub_resetTr
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_microrisc_rpi_io_SimpleIO_stub_1resetTr
  (JNIEnv *, jobject);

/*
 * Class:     com_microrisc_rpi_io_SimpleIO
 * Method:    stub_destroy
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_microrisc_rpi_io_SimpleIO_stub_1destroy
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
