/* 
 * Copyright 2014 MICRORISC s.r.o.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package com.microrisc.simply.asynchrony;

/**
 * Generator of asynchronous messages.
 * 
 * @param <T> type of asynchronous messages, which are generated by this generator
 * 
 * @author Michal Konopa
 */
public interface AsynchronousMessagesGenerator
<T extends BaseAsynchronousMessage> 
{
    /**
     * Registers specified listener for getting data from this generator.
     * @param listener listener to register 
     */
    public void registerListener(AsynchronousMessagesGeneratorListener<T> listener);
    
    /**
     * Unregisters specified listener from this generator.
     * @param listener listener to unregister 
     */
    public void unregisterListener(AsynchronousMessagesGeneratorListener<T> listener);
}
