
package com.microrisc.simply.asynchrony;

/**
 * Generator of asynchronous messages.
 * 
 * @param <T> type of asynchronous messages, which are generated by this generator
 * 
 * @author Michal Konopa
 */
public interface AsynchronousMessagesGenerator
<T extends BaseAsynchronousMessage> 
{
    /**
     * Registers specified listener for getting data from this generator.
     * @param listener listener to register 
     */
    public void registerListener(AsynchronousMessagesGeneratorListener<T> listener);
    
    /**
     * Unregisters specified listener from this generator.
     * @param listener listener to unregister 
     */
    public void unregisterListener(AsynchronousMessagesGeneratorListener<T> listener);
}
