/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_microrisc_rpi_spi_iqrf_SimpleSPI_Master */

#ifndef _Included_com_microrisc_rpi_spi_iqrf_SimpleSPI_Master
#define _Included_com_microrisc_rpi_spi_iqrf_SimpleSPI_Master
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_microrisc_rpi_spi_iqrf_SimpleSPI_Master
 * Method:    stub_initialize
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_microrisc_rpi_spi_iqrf_SimpleSPI_1Master_stub_1initialize
  (JNIEnv *, jobject, jstring);

/*
 * Class:     com_microrisc_rpi_spi_iqrf_SimpleSPI_Master
 * Method:    stub_getSlaveStatus
 * Signature: ()Lcom/microrisc/rpi/spi/iqrf/SPI_Status;
 */
JNIEXPORT jobject JNICALL Java_com_microrisc_rpi_spi_iqrf_SimpleSPI_1Master_stub_1getSlaveStatus
  (JNIEnv *, jobject);

/*
 * Class:     com_microrisc_rpi_spi_iqrf_SimpleSPI_Master
 * Method:    stub_sendData
 * Signature: ([S)V
 */
JNIEXPORT void JNICALL Java_com_microrisc_rpi_spi_iqrf_SimpleSPI_1Master_stub_1sendData
  (JNIEnv *, jobject, jshortArray);

/*
 * Class:     com_microrisc_rpi_spi_iqrf_SimpleSPI_Master
 * Method:    stub_readData
 * Signature: (I)[S
 */
JNIEXPORT jshortArray JNICALL Java_com_microrisc_rpi_spi_iqrf_SimpleSPI_1Master_stub_1readData
  (JNIEnv *, jobject, jint);

/*
 * Class:     com_microrisc_rpi_spi_iqrf_SimpleSPI_Master
 * Method:    stub_destroy
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_microrisc_rpi_spi_iqrf_SimpleSPI_1Master_stub_1destroy
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
